# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0018fa8afa20eba42d6febe620e3fea0169f98701718fd1c2bb4e3a4ccf49d10f73a6f6315f2aa0ec4af5b4aae1b08a5821661dec8288c0b228e4b427e318b60

test:
  secret_key_base: 3747436a14b72ac1eb8d0f7c89a24cd0c0ec17b18066346e3839bb9ff3bd9c6ffaaa911964d7d287200800bd05f0a9fa3821b5e9edef70222b5daf8a7fac696c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
